# Übung Federsysteme

![](Uebung-Federsysteme.png)

**Gesucht:** <br>

- Verschiebungen für $p_1$ und $p_2$
- Federkräfte $N_1$ , $N_2$ und $N_3$

**Gegeben:** <br>

- $c_1=2k$ , $c_2=4k$ , $c_3=k$ , $f_1=3F$ , $f_2=-F$

## Lösung

### notwendige Python Bilbiotheken importieren

In [1]:
import numpy as np

### Steifigkeitsmatritzen (Elemente)

$Ke_1$ = $\left(\begin{array}{rrr} 
2k & -2k \\ 
-2k & 2k \\ 
\end{array}\right)$

$Ke_2$ = $\left(\begin{array}{rrr} 
4k & -4k \\ 
-4k & 4k \\ 
\end{array}\right)$

$Ke_3$ = $\left(\begin{array}{rrr} 
1k & -1k \\ 
-1k & 1k \\ 
\end{array}\right)$

<div class="alert alert-block alert-info">
<b>Hinweis:</b> Da wir numerisch rechnen, setzen wir k=1
</div>

In [2]:
#gegeben
c_list = [2,4,1] #k

Ke = [] # leere Liste anlegen
i=0 # Laufvariable
# Schleife mit allen Einträgen in c_list
for c in c_list:
    i+=1 # Laufvariable + 1
    Ke_i=np.array([[1, -1], [-1, 1]])*c
    Ke.append(Ke_i)
    print("Elementsteifigkeitsmatrix ",i,":\n",Ke_i,"\n")


Elementsteifigkeitsmatrix  1 :
 [[ 2 -2]
 [-2  2]] 

Elementsteifigkeitsmatrix  2 :
 [[ 4 -4]
 [-4  4]] 

Elementsteifigkeitsmatrix  3 :
 [[ 1 -1]
 [-1  1]] 



### Freiheitsgrade (System)

$q_{sys}$ = $\left(\begin{array}{rrr} 
3F \\ 
-F \\ 
\end{array}\right)$

<div class="alert alert-block alert-info">
<b>Hinweis:</b> Da wir numerisch rechnen, setzen wir F=1
</div>

In [3]:
# Lastvektor
q_sys = np.array([[3], [-1]])
print("Lastvektor:\n",q_sys)

Lastvektor:
 [[ 3]
 [-1]]


### Inzidenzmatritzen (Elemente)

$\Lambda_1$ = $\left(\begin{array}{rrr} 
0 & 1 \\ 
0 & 0 \\ 
\end{array}\right)$

$\Lambda_2$ = $\left(\begin{array}{rrr} 
1 & 0 \\ 
0 & 1 \\ 
\end{array}\right)$

$\Lambda_3$ = $\left(\begin{array}{rrr} 
1 & 0 \\ 
0 & 0 \\ 
\end{array}\right)$

In [4]:
inz=[] # leere Liste anlegen
inz.append(np.array([[0, 1], [0, 0]])) #Lambda_1
inz.append(np.array([[1, 0], [0, 1]])) #Lambda_1
inz.append(np.array([[1, 0], [0, 0]])) #Lambda_1

### Steifigkeitsmatrix (System)

$ K_{sys} = \sum_{e=1}^3 {\Lambda^e}^T {K^e} {\Lambda^e} $

In [6]:
K_i=[] # leere Liste anlegen

# Schleife über alle Elemente (Anzahl Einträge von inz)
for i in range(len(inz)):
    K_i.append(np.matmul(np.matmul(np.transpose(inz[i]),Ke[i]),inz[i]))

K_sys=np.sum(K_i, axis=0)
print("Gesamtsteifigkeitsmatrix:\n",K_sys)

NameError: name 'K_ges' is not defined

### Freiheitsgrade (System)

lösen von $p_{sys}$ : <br>
$K_{sys} p_{sys} = q_{sys}$

In [ ]:
p_sys = np.linalg.solve(K_sys, q_sys)
print("Systemfreiheitsgrade p_sys:\n",p_sys,"\n")

print("p_1 =",p_sys[0])
print("p_2 =",p_sys[1])

### Freiheitsgrade (Elemente)

In [ ]:
pe = [] # leere Liste anlegen
# Schleife über alle Elemente (Anzahl Einträge von c_list)
for i in range(len(c_list)):
    pe_i=np.matmul(inz[i],p_sys)
    pe.append(pe_i)
    print("Elementfreiheitsgrad ",i,":\n",pe_i,"\n")

### Federkräfte (Elemente)

In [ ]:
Ne = [] # leere Liste anlegen
i=0 # Laufvariable
# Schleife mit allen Einträgen in c_list
for c in c_list:
    i+=1 # Laufvariable + 1
    Ne_i=c*(pe[i-1][0]-pe[i-1][1]) # ersten Listenindex = 0 (deswegen) i-1)
    Ne.append(Ne_i)
    print("Federkraft N_",i,"=",Ne_i)