# Übung Federsysteme

![](Uebung-Federsysteme.png)

**Gesucht:** <br>

- Verschiebungen für $p_1$ und $p_2$
- Federkräfte $N_1$ , $N_2$ und $N_3$

**Gegeben:** <br>

- $c_1=2k$ , $c_2=4k$ , $c_3=k$ , $f_1=3F$ , $f_2=-F$

## Lösung ohne Verwendung von Listen (übersichtlicher)

<div class="alert alert-block alert-info">
<b>Hinweis:</b> Da keine Listen verwendet werden ist  der Code übersichtlicher, jedoch sind Anpassungen aufwendiger. Weiter unten wird ein Lösungsweg mit der Verwendung von Listen aufgezeigt
</div>


### notwendige Python Bilbiotheken importieren

In [1]:
import numpy as np

### Steifigkeitsmatritzen (Elemente)

$Ke_1$ = $\left(\begin{array}{rrr} 
2k & -2k \\ 
-2k & 2k \\ 
\end{array}\right)$

$Ke_2$ = $\left(\begin{array}{rrr} 
4k & -4k \\ 
-4k & 4k \\ 
\end{array}\right)$

$Ke_3$ = $\left(\begin{array}{rrr} 
1k & -1k \\ 
-1k & 1k \\ 
\end{array}\right)$

<div class="alert alert-block alert-info">
<b>Hinweis:</b> Da wir numerisch rechnen, setzen wir k=1
</div>

In [2]:
#gegeben
c1=2
c2=4
c3=1 
Ke_1 = np.array([[1, -1], [-1, 1]]) * c1
Ke_2 = np.array([[1, -1], [-1, 1]]) * c2
Ke_3 = np.array([[1, -1], [-1, 1]]) * c3

#Ausgabe zur optischen Kontrolle
print("Elementsteifigkeitsmatrix K1 :\n",Ke_1,"\n")
print("Elementsteifigkeitsmatrix K2 :\n",Ke_2,"\n")
print("Elementsteifigkeitsmatrix K3 :\n",Ke_3,"\n")

Elementsteifigkeitsmatrix K1 :
 [[ 2 -2]
 [-2  2]] 

Elementsteifigkeitsmatrix K2 :
 [[ 4 -4]
 [-4  4]] 

Elementsteifigkeitsmatrix K3 :
 [[ 1 -1]
 [-1  1]] 



### Freiheitsgrade (System)

$q_{sys}$ = $\left(\begin{array}{rrr} 
3F \\ 
-F \\ 
\end{array}\right)$

<div class="alert alert-block alert-info">
<b>Hinweis:</b> Da wir numerisch rechnen, setzen wir F=1
</div>

In [3]:
# Lastvektor
q_sys = np.array([[3], [-1]])

#Ausgabe zur optischen Kontrolle
print("Lastvektor:\n",q_sys)

Lastvektor:
 [[ 3]
 [-1]]


### Inzidenzmatritzen (Elemente)

![](Inzidenzmatritzen.png)

$\Lambda_1$ = $\left(\begin{array}{rrr} 
0 & 1 \\ 
0 & 0 \\ 
\end{array}\right)$

$\Lambda_2$ = $\left(\begin{array}{rrr} 
1 & 0 \\ 
0 & 1 \\ 
\end{array}\right)$

$\Lambda_3$ = $\left(\begin{array}{rrr} 
1 & 0 \\ 
0 & 0 \\ 
\end{array}\right)$

In [4]:
inz_1=np.array([[0, 1], [0, 0]]) #Lambda_1
inz_2=np.array([[1, 0], [0, 1]]) #Lambda_2
inz_3=np.array([[1, 0], [0, 0]]) #Lambda_3

#Ausgabe zur optischen Kontrolle
print("Inzidenzmatrix 1 :\n",inz_1,"\n")
print("Inzidenzmatrix 2 :\n",inz_2,"\n")
print("Inzidenzmatrix 3 :\n",inz_3,"\n")

Inzidenzmatrix 1 :
 [[0 1]
 [0 0]] 

Inzidenzmatrix 2 :
 [[1 0]
 [0 1]] 

Inzidenzmatrix 3 :
 [[1 0]
 [0 0]] 



### Steifigkeitsmatrix (System)

$ K_{sys} = \sum_{e=1}^3 {\Lambda^e}^T {K^e} {\Lambda^e} $

In [5]:
Ksyspart_1 = np.matmul(np.matmul(np.transpose(inz_1),Ke_1),inz_1)
Ksyspart_2 = np.matmul(np.matmul(np.transpose(inz_2),Ke_2),inz_2)
Ksyspart_3 = np.matmul(np.matmul(np.transpose(inz_3),Ke_3),inz_3)

K_sys= Ksyspart_1 + Ksyspart_2 + Ksyspart_3
#Ausgabe zur optischen Kontrolle
print("Gesamtsteifigkeitsmatrix:\n",K_sys)

Gesamtsteifigkeitsmatrix:
 [[ 5 -4]
 [-4  6]]


### Freiheitsgrade (System)

lösen von $p_{sys}$ : <br>
$K_{sys} p_{sys} = q_{sys}$

In [6]:
p_sys = np.linalg.solve(K_sys, q_sys)
print("Systemfreiheitsgrade p_sys:\n",p_sys,"\n")

#Ausgabe der Lösung
print("Lösung: p_1 =",p_sys[0])
print("Lösung: p_2 =",p_sys[1])

Systemfreiheitsgrade p_sys:
 [[1. ]
 [0.5]] 

Lösung: p_1 = [1.]
Lösung: p_2 = [0.5]


### Freiheitsgrade (Elemente)

In [7]:
pe_1=np.matmul(inz_1,p_sys)
pe_2=np.matmul(inz_2,p_sys)
pe_3=np.matmul(inz_3,p_sys)

#Ausgabe zur optischen Kontrolle
print("Elementfreiheitsgrad 1:\n",pe_1,"\n")
print("Elementfreiheitsgrad 2:\n",pe_2,"\n")
print("Elementfreiheitsgrad 3:\n",pe_3,"\n")

Elementfreiheitsgrad 1:
 [[0.5]
 [0. ]] 

Elementfreiheitsgrad 2:
 [[1. ]
 [0.5]] 

Elementfreiheitsgrad 3:
 [[1.]
 [0.]] 



### Federkräfte (Elemente)

In [8]:
Ne_1 = c1*(pe_1[0]-pe_1[1])
Ne_2 = c2*(pe_2[0]-pe_2[1])
Ne_3 = c3*(pe_3[0]-pe_3[1])

#Ausgabe der Lösung
print("Lösung: Federkraft N_1:",Ne_1)
print("Lösung: Federkraft N_2:",Ne_2)
print("Lösung: Federkraft N_3:",Ne_3)

Lösung: Federkraft N1: [1.]
Lösung: Federkraft N2: [2.]
Lösung: Federkraft N3: [1.]


## Lösung mit der Verwendung von Listen (Fortgeschritten)

<div class="alert alert-block alert-info">
<b>Hinweis:</b> Die Verwendung von Listen sieht kompliziert aus, vereinfacht aber die Eingabe, weil weniger geändert werden muss
</div>


### notwendige Python Bilbiotheken importieren

In [9]:
import numpy as np

### Steifigkeitsmatritzen (Elemente)

$Ke_1$ = $\left(\begin{array}{rrr} 
2k & -2k \\ 
-2k & 2k \\ 
\end{array}\right)$

$Ke_2$ = $\left(\begin{array}{rrr} 
4k & -4k \\ 
-4k & 4k \\ 
\end{array}\right)$

$Ke_3$ = $\left(\begin{array}{rrr} 
1k & -1k \\ 
-1k & 1k \\ 
\end{array}\right)$

<div class="alert alert-block alert-info">
<b>Hinweis:</b> Da wir numerisch rechnen, setzen wir k=1
</div>

In [10]:
#gegeben
c_list = [2,4,1] #k

Ke = [] # leere Liste anlegen
i=0 # Laufvariable
# Schleife mit allen Einträgen in c_list
for c in c_list:
    i+=1 # Laufvariable + 1
    Ke_i=np.array([[1, -1], [-1, 1]])*c
    Ke.append(Ke_i)
    #Ausgabe zur optischen Kontrolle
    print("Elementsteifigkeitsmatrix ",i,":\n",Ke_i,"\n")


Elementsteifigkeitsmatrix  1 :
 [[ 2 -2]
 [-2  2]] 

Elementsteifigkeitsmatrix  2 :
 [[ 4 -4]
 [-4  4]] 

Elementsteifigkeitsmatrix  3 :
 [[ 1 -1]
 [-1  1]] 



### Freiheitsgrade (System)

$q_{sys}$ = $\left(\begin{array}{rrr} 
3F \\ 
-F \\ 
\end{array}\right)$

<div class="alert alert-block alert-info">
<b>Hinweis:</b> Da wir numerisch rechnen, setzen wir F=1
</div>

In [11]:
# Lastvektor
q_sys = np.array([[3], [-1]])

#Ausgabe zur optischen Kontrolle
print("Lastvektor:\n",q_sys)

Lastvektor:
 [[ 3]
 [-1]]


### Inzidenzmatritzen (Elemente)

![](Inzidenzmatritzen.png)

$\Lambda_1$ = $\left(\begin{array}{rrr} 
0 & 1 \\ 
0 & 0 \\ 
\end{array}\right)$

$\Lambda_2$ = $\left(\begin{array}{rrr} 
1 & 0 \\ 
0 & 1 \\ 
\end{array}\right)$

$\Lambda_3$ = $\left(\begin{array}{rrr} 
1 & 0 \\ 
0 & 0 \\ 
\end{array}\right)$

In [12]:
inz=[] # leere Liste anlegen
inz.append(np.array([[0, 1], [0, 0]])) #Lambda_1
inz.append(np.array([[1, 0], [0, 1]])) #Lambda_2
inz.append(np.array([[1, 0], [0, 0]])) #Lambda_3

#Ausgabe zur optischen Kontrolle
i=0
for inz_i in inz: i+=1;print("Inzidenzmatrix",i,":\n",inz_i,"\n")

Inzidenzmatrix 1 :
 [[0 1]
 [0 0]] 

Inzidenzmatrix 2 :
 [[1 0]
 [0 1]] 

Inzidenzmatrix 3 :
 [[1 0]
 [0 0]] 



### Steifigkeitsmatrix (System)

$ K_{sys} = \sum_{e=1}^3 {\Lambda^e}^T {K^e} {\Lambda^e} $

In [13]:
K_i=[] # leere Liste anlegen

# Schleife über alle Elemente (Anzahl Einträge von inz)
for i in range(len(inz)):
    K_i.append(np.matmul(np.matmul(np.transpose(inz[i]),Ke[i]),inz[i]))

K_sys=np.sum(K_i, axis=0)

#Ausgabe zur optischen Kontrolle
print("Gesamtsteifigkeitsmatrix:\n",K_sys)

Gesamtsteifigkeitsmatrix:
 [[ 5 -4]
 [-4  6]]


### Freiheitsgrade (System)

lösen von $p_{sys}$ : <br>
$K_{sys} p_{sys} = q_{sys}$

In [14]:
p_sys = np.linalg.solve(K_sys, q_sys)
print("Systemfreiheitsgrade p_sys:\n",p_sys,"\n")

#Ausgabe der Lösung
print("Lösung: p_1 =",p_sys[0])
print("Lösung: p_2 =",p_sys[1])

Systemfreiheitsgrade p_sys:
 [[1. ]
 [0.5]] 

Lösung: p_1 = [1.]
Lösung: p_2 = [0.5]


### Freiheitsgrade (Elemente)

In [15]:
pe = [] # leere Liste anlegen
# Schleife über alle Elemente (Anzahl Einträge von c_list)
for i in range(len(c_list)):
    pe_i=np.matmul(inz[i],p_sys)
    pe.append(pe_i)
    #Ausgabe zur optischen Kontrolle
    print("Elementfreiheitsgrad ",i,":\n",pe_i,"\n")

Elementfreiheitsgrad  0 :
 [[0.5]
 [0. ]] 

Elementfreiheitsgrad  1 :
 [[1. ]
 [0.5]] 

Elementfreiheitsgrad  2 :
 [[1.]
 [0.]] 



### Federkräfte (Elemente)

In [16]:
Ne = [] # leere Liste anlegen
i=0 # Laufvariable
# Schleife mit allen Einträgen in c_list
for c in c_list:
    i+=1 # Laufvariable + 1
    Ne_i=c*(pe[i-1][0]-pe[i-1][1]) # ersten Listenindex = 0 (deswegen) i-1)
    Ne.append(Ne_i)
    #Ausgabe der Lösung
    print("Lösung: Federkraft N_",i,"=",Ne_i)

Lösung: Federkraft N_ 1 = [1.]
Lösung: Federkraft N_ 2 = [2.]
Lösung: Federkraft N_ 3 = [1.]
