# Grundlagen

aus https://numpy.org/doc/stable/user/absolute_beginners.html

## basic arrays

In [13]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Null Array

In [7]:
np.zeros(2)

array([0., 0.])

## Ein Array

In [8]:
np.ones(2)

array([1., 1.])

## Array mit range

In [9]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

## Array mit Einteilung

In [10]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## sortieren

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])